/* Ledger — the independent financial ledger (read-only; generated by txns). */
import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '@core/auth/AuthContext';
import { AXBadge, AXPagination, AXSelect, AXTable, type AXColumn, type AXPageMeta } from '@ui/ax';
import { financeApi, type LedgerEntry } from './api';

export function LedgerPage() {
  const { user } = useAuth();
  const [rows, setRows] = useState<LedgerEntry[]>([]);
  const [meta, setMeta] = useState<AXPageMeta>({
    current_page: 1,
    last_page: 1,
    total: 0,
    per_page: 25,
  });
  const [page, setPage] = useState(1);
  const [type, setType] = useState('');

  const load = useMemo(
    () => () => {
      financeApi
        .ledger({ page, filter: { school_id: user?.school_id, entry_type: type } })
        .then((r) => {
          setRows(r.data);
          setMeta(r.meta);
        });
    },
    [page, type, user?.school_id]
  );
  useEffect(() => {
    load();
  }, [load]);

  const columns: AXColumn<LedgerEntry>[] = [
    { key: 'date', header: 'Date', render: (r) => r.entry_date ?? '—' },
    {
      key: 'type',
      header: 'Type',
      render: (r) => (
        <AXBadge tone={r.entry_type === 'credit' ? 'green' : 'red'}>{r.entry_type}</AXBadge>
      ),
    },
    { key: 'amount', header: 'Amount', render: (r) => `₹${r.amount}` },
    { key: 'source', header: 'Source', render: (r) => `${r.source_type} #${r.source_id}` },
    { key: 'narration', header: 'Narration', render: (r) => r.narration ?? '—' },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <i className="fas fa-book text-[var(--navy-primary)]" />
          <h2 className="text-lg font-semibold text-[var(--navy-primary)]">Financial Ledger</h2>
          <AXBadge tone="gray">independent of payments</AXBadge>
        </div>
        <div className="w-40">
          <AXSelect
            value={type}
            onChange={(e) => {
              setType(e.target.value);
              setPage(1);
            }}
            options={[
              { value: '', label: 'All entries' },
              { value: 'credit', label: 'Credit' },
              { value: 'debit', label: 'Debit' },
            ]}
          />
        </div>
      </div>

      <AXTable columns={columns} rows={rows} rowKey={(r) => r.id} empty="No ledger entries yet." />
      <AXPagination meta={meta} onPage={setPage} />
    </div>
  );
}
