<?php

declare(strict_types=1);

namespace App\Modules\Payroll\Services;

use App\Modules\Payroll\Enums\SettlementStatus;
use App\Modules\Payroll\Models\Payslip;
use App\Platform\Shared\Services\BaseCrudService;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Read + settlement over payslips. Payslips are generated by the Payroll Engine;
 * this service lists/finds them (lines + employee identity for QR) and records
 * the payroll-side settlement status (Finance records the actual payment).
 */
class PayslipService extends BaseCrudService
{
    protected function model(): string
    {
        return Payslip::class;
    }

    protected function withRelations(Builder $query): void
    {
        $query->with([
            'lines',
            'employee:id,name,employee_number,identity_id',
            'employee.identity:id,identity_number,barcode_value,public_identifier,owner_type,owner_id',
        ]);
    }

    protected function filterable(): array
    {
        return ['school_id', 'run_id', 'staff_id', 'period_year', 'period_month', 'settlement_status'];
    }

    protected function sortable(): array
    {
        return ['id', 'period_year', 'period_month'];
    }

    /**
     * @return array<string, array{type:string, columns?:array<int,string>, enum?:string, relation?:string}>
     */
    protected function searchDefinitions(): array
    {
        return [
            'payslip_number' => ['type' => 'text', 'columns' => ['payslip_number']],
            'settlement_status' => ['type' => 'enum', 'enum' => SettlementStatus::class],
            'employee' => ['type' => 'relation', 'relation' => 'employee', 'columns' => ['name', 'employee_number']],
        ];
    }

    public function find(int|string $id): Model
    {
        $query = $this->query();
        $this->withRelations($query);

        return $query->findOrFail($id);
    }

    /** Record the payroll-side settlement status (Finance records the actual payment). */
    public function settle(Payslip $payslip, SettlementStatus $status): Payslip
    {
        $payslip->update(['settlement_status' => $status->value]);

        return $payslip->refresh();
    }
}
